language: node_js
node_js:
  - "11.0"
git:
  quiet: true
branches:
  only:
    - master
    - develop
    - /^release-.*$/
install:
  - npm install
  - cd functions && npm install
  - cd ../
script:
  - npm run ng build -- --prod
cache: npm
deploy:
  skip_cleanup: true
  provider: firebase
  project: digital-health-assistant
  token:
    secure: "1/SHOTfvw2RAQ_KDdwERnQWBQc_kIE-eBHhtY-yJP4T7A"

