name: $(BuildDefinitionName)_$(SourceBranchName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'
- script: npm run ng build -- --prod
  displayName: 'npm build'
- task: PublishBuildArtifacts@1
  displayName: publish artifacts
  inputs:
    PathtoPublish: 'dist/dha'
    ArtifactName: 'files'
    publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  displayName: publish release artifacts
  inputs:
    PathtoPublish: 'firebase.json'
    ArtifactName: 'deploy'
    publishLocation: 'Container'
