name: digital-health-assistant

on:
  push:
    paths:
      - 'functions/**'
      - 'src/**'
      - 'angular.json'
      - '.firebaserc'
      - '.github/workflows/**'
      - 'firebase.json'
      - 'firestore.indexes.json'
      - 'firestore.rules'
      - 'ngsw-config.json'
      - 'package.json'
      - 'package-lock.json'
      - 'storage.rules'
      - 'tsconfig.json'
      - 'tsconfig.app.json'
      - 'tsconfig.spec.json'
    branches:
    - develop
    - master
    - release/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Angular npm install
      run: npm install
    - name: Angular build
      run: npm run ng build -- --prod
    - name: Publish artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dist
        path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Functions npm install
        run: |
          cd functions
          npm install
      - name: Download Artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
